server:
  port: 8080

spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:~/spring-boot-h2-db
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update

url:
  validacao:
    cooperativado: https://user-info.herokuapp.com